version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kirillshirokov/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    image: kirillshirokov/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: kirillshirokov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static